[font]
size = 13

[font.normal]
# family = "RecMonoCasual Nerd Font"
style = "Semibold"

[window]
opacity = 0.7


[window.padding]
x = 5
y = 5

[window.dimensions]
columns = 80
lines = 30


[cursor.style]
shape = "Underline"
blinking = "Always"
