[font]
size = 15

[font.normal]
family = "CaskaydiaCove Nerd Font"
style = "Retina"

[window]
opacity = 0.7


[window.padding]
x = 15
y = 15

[window.dimensions]
columns = 80
lines = 30


[cursor.style]
shape = "Underline"
blinking = "Always"
