[font]
size = 12

[font.normal]
family = "CaskaydiaCove Nerd Font"
style = "Retina"

[window]
opacity = 0.7


[window.padding]
x = 5
y = 5

[window.dimensions]
columns = 80
lines = 30


[cursor.style]
shape = "Underline"
blinking = "Always"
