[font]
size = 15

[font.normal]
family = "FiraCode Nerd Font Propo"
style = "Retina"

[window]
opacity = 0.6

[window.padding]
x = 15
y = 15

[window.dimensions]
columns = 80 
lines = 30

[cursor.style]
shape = "Underline"
blinking = "Always"
