###################
### MY PROGRAMS ###
###################

# See https://wiki.hypr.land/Configuring/Keywords/

# Set programs that you use
$terminal = kitty
$browser = zen-browser
$fileManager = dolphin
$menu = $HOME/.config/hypr/scripts/launcher-apps.sh
