# --- Terminal & Colors ---
set -g default-terminal "tmux-256color"

# Ensure truecolor and OSC passthrough match both xterm and tmux terminal definitions
set -as terminal-overrides ",xterm-256color:Tc,tmux-256color:Tc"
set -as terminal-features ",xterm-256color:osc,tmux-256color:osc"

# Allow applications to pass codes through to the terminal
set -gq allow-passthrough on

# --- Behavior ---
# Fix Esc delay in Vim/Neovim
set -sg escape-time 10

# Mouse and System interaction
set -g mouse on
set -g renumber-windows on
set -s set-clipboard on

# Allow applications to pass codes through to the terminal (e.g., OSC 52)
set -gq allow-passthrough on

# --- History ---
set -g history-limit 10000
