- name: Copy GRUB configuration
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/../files/grub"
    dest: /etc/default/grub
    owner: root
    group: root
    mode: '0644'
  become: yes

- name: Update GRUB
  ansible.builtin.command:
    cmd: grub-mkconfig -o /boot/grub/grub.cfg
  become: yes