--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/codesmith28/wallpaper/src/night_ship.jpg"

-- Special
background="#0C0F17"
foreground="#c1cbcc"
cursor="#c1cbcc"

-- Colors
color0="#0C0F17"
color1="#325269"
color2="#4F626D"
color3="#A37958"
color4="#4D7489"
color5="#6B919F"
color6="#76B0C5"
color7="#c1cbcc"
color8="#878e8e"
color9="#325269"
color10="#4F626D"
color11="#A37958"
color12="#4D7489"
color13="#6B919F"
color14="#76B0C5"
color15="#c1cbcc"
