--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/codesmith28/wallpaper/src/aurora_borealis.jpg"

-- Special
background="#071618"
foreground="#93e0d0"
cursor="#93e0d0"

-- Colors
color0="#071618"
color1="#169972"
color2="#553190"
color3="#2D628A"
color4="#5B5B9F"
color5="#A66CBB"
color6="#239F9A"
color7="#93e0d0"
color8="#669c91"
color9="#169972"
color10="#553190"
color11="#2D628A"
color12="#5B5B9F"
color13="#A66CBB"
color14="#239F9A"
color15="#93e0d0"
