# Shell variables
# Generated by 'wal'
wallpaper='/home/codesmith28/wallpaper/src/dune_night_v2_1.jpg'

# Special
background='#050C1E'
foreground='#97abb0'
cursor='#97abb0'

# Colors
color0='#050C1E'
color1='#102540'
color2='#192C47'
color3='#273A52'
color4='#2D465A'
color5='#2F5368'
color6='#33657A'
color7='#97abb0'
color8='#69777b'
color9='#102540'
color10='#192C47'
color11='#273A52'
color12='#2D465A'
color13='#2F5368'
color14='#33657A'
color15='#97abb0'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
