--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/codesmith28/wallpaper/src/dune_night_v2_1.jpg"

-- Special
background="#050C1E"
foreground="#97abb0"
cursor="#97abb0"

-- Colors
color0="#050C1E"
color1="#102540"
color2="#192C47"
color3="#273A52"
color4="#2D465A"
color5="#2F5368"
color6="#33657A"
color7="#97abb0"
color8="#69777b"
color9="#102540"
color10="#192C47"
color11="#273A52"
color12="#2D465A"
color13="#2F5368"
color14="#33657A"
color15="#97abb0"
