--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/codesmith28/wallpaper/src/secluded-grove-pixel.png"

-- Special
background="#011219"
foreground="#e2e9e2"
cursor="#e2e9e2"

-- Colors
color0="#011219"
color1="#52686F"
color2="#6C8978"
color3="#5F7582"
color4="#738A8C"
color5="#93A59E"
color6="#BAC8C2"
color7="#e2e9e2"
color8="#9ea39e"
color9="#52686F"
color10="#6C8978"
color11="#5F7582"
color12="#738A8C"
color13="#93A59E"
color14="#BAC8C2"
color15="#e2e9e2"
