# Shell variables
# Generated by 'wal'
wallpaper='/home/codesmith28/wallpaper/src/night_ship.jpg'

# Special
background='#0C0F17'
foreground='#c1cbcc'
cursor='#c1cbcc'

# Colors
color0='#0C0F17'
color1='#325269'
color2='#4F626D'
color3='#A37958'
color4='#4D7489'
color5='#6B919F'
color6='#76B0C5'
color7='#c1cbcc'
color8='#878e8e'
color9='#325269'
color10='#4F626D'
color11='#A37958'
color12='#4D7489'
color13='#6B919F'
color14='#76B0C5'
color15='#c1cbcc'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
