# Shell variables
# Generated by 'wal'
wallpaper='/home/codesmith28/wallpaper/src/path.jpg'

# Special
background='#090e0a'
foreground='#bdbca3'
cursor='#bdbca3'

# Colors
color0='#090e0a'
color1='#2F4C29'
color2='#336127'
color3='#525B2A'
color4='#3C4E44'
color5='#556652'
color6='#638C4A'
color7='#bdbca3'
color8='#848372'
color9='#2F4C29'
color10='#336127'
color11='#525B2A'
color12='#3C4E44'
color13='#556652'
color14='#638C4A'
color15='#bdbca3'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
