################
### MONITORS ###
################

# See https://wiki.hypr.land/Configuring/Monitors/
# monitor=,highres,auto,auto

# Optional mirror presets:
monitor = ,highres, auto, 1, mirror, eDP-1
# monitor = ,highres, auto, 1, mirror, HDMI-A-1
