[metadata]
name = "files"
description = "A channel to select files and directories"
requirements = ["fdfind", "bat"]

[source]
command = "fdfind -t f"

[preview]
command = "bat -n --color=always '{}'"
env = { BAT_THEME = "Catppuccin Mocha" }

[ui]
preview_panel = { size = 70, scrollbar = true }

[keybindings]
quit = "q"
reload_source = "F5"
confirm_selection = "F12" # pressing F12 will now trigger our custom action

[actions.confirm_selection] # overriding the built-in confirm_selection
description = "Opens the selected entries with the default editor (falls back to vim)"
command = "${EDITOR:-vim} {}"
mode = "execute"

[actions.rm]
description = "Removes the selected entries"
command = "rm {}"
