contact_links:
  - name: Idea, Enhancement, Question, Support
    url: https://github.com/jarun/nnn/discussions
    about: If you have a question, need support or want to discuss new ideas then please open a discussion thread.
