return {
    require "plugins.assistant_nvim",
    require "plugins.copilot_zbir",
    -- require "plugins.formatter",
    require "plugins.indent_blankline_nvim",
    require "plugins.lazygit_nvim",
    require "plugins.mason_nvim",
    require "plugins.mini_indentscope",
    require "plugins.navigator",
    require "plugins.noice_nvim",
    require "plugins.nvim_lspconifg",
    require "plugins.nvim_notify",
    require "plugins.nvim_surround",
    require "plugins.nvim_tree",
    require "plugins.nvim_treesitter",
    require "plugins.nvim_ts_autotag",
    require "plugins.oil_nvim",
    require "plugins.outline_nvim",
    require "plugins.rainbow_csv",
    require "plugins.render_markdown",
    require "plugins.snippets",
    require "plugins.telescope",
    require "plugins.vim_wakatime",
}
