# Codesmith28 environment:

env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland
env = QT_QPA_PLATFORM,wayland
env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1
env = QT_AUTO_SCREEN_SCALE_FACTOR,1
env = MOZ_ENABLE_WAYLAND,1
env = GDK_SCALE,1
env = WLR_NO_HARDWARE_CURSORS, 1
env = HYPRSHOT_DIR, /home/codesmith28/Pictures/Screenshots/

# kvm:
env = WLR_RENDERER_ALLOW_SOFTWARE, 1
env = XDG_CURRENT_DESKTOP,Unity

# nvidia:
# env = LIBVA_DRIVER_NAME,nvidia
# env = XDG_SESSION_TYPE,wayland
# env = GBM_BACKEND,nvidia-drm
# env = __GLX_VENDOR_LIBRARY_NAME,nvidia

# env = __GL_VRR_ALLOWED,1
# env = WLR_DRM_NO_ATOMIC,1
