# Modular Hyprland config entrypoint.

source = ~/.config/hypr/conf.d/monitors.conf
source = ~/.config/hypr/conf.d/programs.conf
source = ~/.config/hypr/conf.d/autostart.conf
source = ~/.config/hypr/conf.d/environment.conf
source = ~/.config/hypr/conf.d/look-and-feel.conf
source = ~/.config/hypr/conf.d/input.conf
source = ~/.config/hypr/conf.d/variables.conf
source = ~/.config/hypr/conf.d/keybindings.conf
source = ~/.config/hypr/conf.d/rules.conf
