--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/codesmith28/wallpaper/src/path.jpg"

-- Special
background="#090e0a"
foreground="#bdbca3"
cursor="#bdbca3"

-- Colors
color0="#090e0a"
color1="#2F4C29"
color2="#336127"
color3="#525B2A"
color4="#3C4E44"
color5="#556652"
color6="#638C4A"
color7="#bdbca3"
color8="#848372"
color9="#2F4C29"
color10="#336127"
color11="#525B2A"
color12="#3C4E44"
color13="#556652"
color14="#638C4A"
color15="#bdbca3"
